### PR TITLE
added key for elements

### PR DESCRIPTION
**Pull request by vikashgraja**
Added key for each elements in filters so we can use multiple DynamicFilters in one app

### CODE REVIEW

**Comment by Sairam90** [comment]
This would be a helpful feature as currently if there are more than one filters with the same fields on a page; we get a DuplicateWidgetID error

Any timelines on when this will be merged ?

**Comment by vikashgraja** [comment]
Yeah, It will be merged soon

**Comment by arsentievalex** [comment]
thanks @vikashgraja just merged your commit

**Comment by arsentievalex** [comment]
@Sairam90 the new version streamlit-dynamic-filters 0.1.7 is on pypi

**Comment by Sairam90** [comment]
@arsentievalex Thank you!

**Comment by Sairam90** [comment]
Hi @arsentievalex , I am able to download the new version but my script is not able to import any classes from the lib as it's not recognized
ex: import streamlit_dynamic_filters or from streamlit_dynamic_filter import DynamicFilters doesnt work

**Comment by arsentievalex** [comment]
@Sairam90 thanks for the info, there was an issue with naming. it should be fixed in the latest version, pls use:
pip install streamlit-dynamic-filters==0.1.9

**Comment by Sairam90** [comment]
@arsentievalex Thank you!, works fine now :)

**Pull request merged**
